version: "3.2"
services:
  api:
    container_name: mapsf_api
    build:
      context: ./api
      args:
        - DOCKER_GOLANG_PORT=${DOCKER_GOLANG_PORT}
        - REPOSITORY_NAME=${REPOSITORY_NAME}
    volumes:
      - ./api:/go/src/github.com/${REPOSITORY_NAME}
    links:
      - db
      - redis
    environment:
      - APP_ENV=${APP_ENV}
      - DB_HOST=${POSTGRES_HOST}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - PORT=${DOCKER_GOLANG_PORT}
      - REDIS_HOST=${DOCKER_REDIS_HOST}
      - REDIS_PORT=${DOCKER_REDIS_PORT}
      - API_HOST=${API_HOST}
    depends_on:
     - db
     - redis
  db:
    #container_name: jilexandr_db
    build: ./db
    volumes:
      - ./db/pgdata:/pgdata
    ports:
      - "${DB_SHARED_PORT}:${DOCKER_DB_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/pgdata
  redis:
    #container_name: jilexandr_redis
    build:
      context: ./redis
    ports:
      - "${REDIS_SHARED_PORT}:${DOCKER_REDIS_PORT}"
  nginx:
    #container_name: jilexandr_nginx
    build:
      context: ./nginx
    environment:
     - API_HOST=${API_HOST}
    ports:
      - ${NGINX_SHARED_PORT}:80
    links:
      - api
    depends_on:
      - api